### ISSUE TITLE
我想在本地训练模型，运行后出现CPU training is not allowed.

### ISSUE THREAD

**Issue by Apoil** [SayaSS/vits-finetuning#10]
这是设置的问题，还是本地显卡基础配置的问题？我该如何使用GPU训练，

**Comment by SayaSS** [comment]
需要NVIDIA显卡以及cuda环境，并且torch能支持GPU

**Comment by Apoil** [comment]
> 需要NVIDIA显卡以及cuda环境，并且torch能支持GPU

好的谢谢
