### ISSUE TITLE
调整数据集后训练报错

### ISSUE THREAD

**Issue by dolphin17** [SayaSS/vits-finetuning#13]
我只挑选了miyu一条数据进行训练，训练的时候报下面这个错误，能帮忙看看吗
  File "/data1/ai/vits-finetuning/data_utils.py", line 358, in __iter__
    ids_bucket = ids_bucket + ids_bucket * (rem // len_bucket) + ids_bucket[:(rem % len_bucket)]
ZeroDivisionError: integer division or modulo by zero

**Comment by SayaSS** [comment]
因为1条数据集真的太少了。。

**Comment by dolphin17** [comment]
感觉跟音频有关系，我换其他音频就可以。这个可以训练44khz的吗，如果可以需要调整哪几个参数就可以了，目前就看到一个sampling_rate这个参数

**Comment by SayaSS** [comment]
不能

**Comment by dolphin17** [comment]
这边微调模型能微调其他人的模型吗？我看都需要G和D这两个文件，别人的模型文件只要一个G文件，这样能微调运行的吗？

**Comment by SayaSS** [comment]
不能的，生成器和判断器都需要

**Comment by dolphin17** [comment]
那怎么搞，我看别人只给了一个G文件，那没法微调。或者说有没哪里可以找到比较多的可以微调的模型？
