### ISSUE TITLE
TypeError: mel() takes 0 positional arguments but 5 were given

### ISSUE THREAD

**Issue by ghost** [SayaSS/vits-finetuning#14]
大佬您好！请问在服务器上训练出现这个错误是为什么呢？
![2YDAP@B$AK$D992P5ABS_)Y](https://user-images.githubusercontent.com/52548756/222733134-6ee9880c-1432-4e57-b9e9-4564c53f7737.png)

**Comment by SayaSS** [comment]
参考 #12 的处理方式

**Comment by ghost** [comment]
> 参考 #12 的处理方式

谢谢！
