### ISSUE TITLE
  for audiopath, text in self.audiopaths_and_text: ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by axlmly** [SayaSS/vits-finetuning#16]
WARNING:checkpoints:E:\BaiduNetdiskDownload\vits-finetuning-main is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
Traceback (most recent call last):
  File "train.py", line 302, in <module>
    main()
  File "train.py", line 56, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\anaconda\envs\1\lib\site-packages\torch\multiprocessing\spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\anaconda\envs\1\lib\site-packages\torch\multiprocessing\spawn.py", line 197, in start_processes
    while not context.join():
  File "D:\anaconda\envs\1\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "D:\anaconda\envs\1\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "E:\BaiduNetdiskDownload\vits-finetuning-main\train.py", line 72, in run
    train_dataset = TextAudioLoader(hps.data.training_files, hps.data)
  File "E:\BaiduNetdiskDownload\vits-finetuning-main\data_utils.py", line 38, in __init__
    self._filter()
  File "E:\BaiduNetdiskDownload\vits-finetuning-main\data_utils.py", line 51, in _filter
    for audiopath, text in self.audiopaths_and_text:
ValueError: too many values to unpack (expected 2)
用train.py不行不知道为什么,train_ms.py可以但是用的cpu占用.

**Comment by SayaSS** [comment]
你好，默认需要使用train_ms.py。至于cpu占用，我没能理解你的意思，能否提供下更详细的描述？

**Comment by axlmly** [comment]
> 

就是在训练过程中使用的是cpu资源而不是gpu,我在train_ms.py里面有看到assert torch.cuda.is_available()这一行,应该是说有调用吧,但是我在任务管理器看的gpu基本上没有调用.pytorch也是gpu版本的
![Taskmgr_LZ4ixtqqmJ](https://user-images.githubusercontent.com/41771421/225205532-bd5c05be-6770-46d4-9ec1-4ead14a86331.png)

**Comment by SayaSS** [comment]
你这里显示调用的是GPU的copy引擎，负责GPU与其他部分的数据传输，利用率不高但还是有调度的，并没有什么问题，看cuda引擎的利用率和显存占用就可以了。
可以在命令行使用`nvidia-smi -lms 100`指令查看GPU实时情况

**Comment by axlmly** [comment]
> 你这里显示调用的是GPU的copy引擎，负责GPU与其他部分的数据传输，利用率不高但还是有调度的，并没有什么问题，看cuda引擎的利用率和显存占用就可以了。 可以在命令行使用`nvidia-smi -lms 100`指令查看GPU实时情况

确实有起伏,可是我更改配置文件里的batch_size数值调高调低都没什么变化,目前设为6,在8000步训练的到的效果差了很多,基本上全是杂音,完全不如云端运行这是什么原因?本地部署有参考https://www.bilibili.com/read/cv21153903这位.
![Taskmgr_aphaRgl08d](https://user-images.githubusercontent.com/41771421/225215912-d0803860-f659-46d5-8def-9a2e2f03718f.png)

**Comment by SayaSS** [comment]
`batch_size`的修改主要影响显存的占用率，小范围的修改并不会有太大的变动。
全是电音可能是因为你没有正确加载预训练模型。
在完全没有训练过的情况下，训练脚本运行后能看到以下类似的输出，才代表加载了预训练模型
```
INFO:checkpoints:Loaded checkpoint 'XXXXXX/G_0.pth' (iteration 0)
INFO:checkpoints:Loaded checkpoint 'XXXXXX/D_0.pth' (iteration 0)
```

**Comment by axlmly** [comment]
> `batch_size`的修改主要影响显存的占用率，小范围的修改并不会有太大的变动。
> 全是电音可能是因为你没有正确加载预训练模型。
> 在完全没有训练过的情况下，训练脚本运行后能看到以下类似的输出，才代表加载了预训练模型
> ```
> INFO:checkpoints:Loaded checkpoint 'XXXXXX/G_0.pth' (iteration 0)
> INFO:checkpoints:Loaded checkpoint 'XXXXXX/D_0.pth' (iteration 0)
> ```

云端的info后面checkpoints跟着的是seving，本地部署也是，只有在第二次部署才能出现load字样，这还是加载进度。预训练模型全部放进checkpoints文件夹里面了，出现角色名字说明也能读取的到。所以读取不到预训练模型的话该怎么办呢，是要在drive那边也要放一份吗？突然发现vits目录里面没有chekpoints文件夹

**Comment by SayaSS** [comment]
我并不太能读的懂你的文字哦。。比如`seving`、`这还是加载进度`，没法理解是什么意思
角色名字是从config里读取的，预训练模型的放置位置请参考readme

**Comment by axlmly** [comment]
> 我并不太能读的懂你的文字哦。。比如、，没法理解是什么意思 角色名字是从config里读取的，预训练模型的放置位置请参考自述文件`seving``这还是加载进度`

抱歉,我把预训练模型放的位置和onnx转换搞混了,已经没有问题三连了
