### ISSUE TITLE
您好，关于谷歌colab训练的问题

### ISSUE THREAD

**Issue by boypjm998** [SayaSS/vits-finetuning#7]
我今天早上尝试使用谷歌colab训练的时候，在安装依赖的时候出现了如下版本问题：
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xarray-einstats 0.5.1 requires scipy>=1.6, but you have scipy 1.5.2 which is incompatible.
torchtext 0.14.1 requires torch==1.13.1, but you have torch 1.6.0 which is incompatible.
torchaudio 0.13.1+cu116 requires torch==1.13.1, but you have torch 1.6.0 which is incompatible.
tensorflow 2.11.0 requires tensorboard<2.12,>=2.11, but you have tensorboard 2.3.0 which is incompatible.
googleapis-common-protos 1.58.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-translate 3.8.4 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-language 2.6.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-firestore 2.7.3 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-datastore 2.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-bigquery 3.4.2 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-cloud-bigquery-storage 2.18.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
google-api-core 2.11.0 requires google-auth<3.0dev,>=2.14.1, but you have google-auth 1.35.0 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.19.0 which is incompatible.
fastai 2.7.11 requires torch<1.14,>=1.7, but you have torch 1.6.0 which is incompatible.
fastai 2.7.11 requires torchvision>=0.8.2, but you have torchvision 0.7.0 which is incompatible.`
`
这个问题在之前都是没有出现的，然后运行预处理和训练模型代码的时候，甚至没有进入main方法，就有错误信息出现。

`File "train_ms.py", line 23, in <module>
    from data_utils import (
File "/content/vits-finetuning/vits-finetuning/data_utils.py", line 11, in <module>
    from text import text_to_sequence, cleaned_text_to_sequence
File "/content/vits-finetuning/vits-finetuning/text/__init__.py", line 2, in <module>
    from text import cleaners
File "/content/vits-finetuning/vits-finetuning/text/cleaners.py", line 2, in <module>
    from text.japanese import japanese_to_romaji_with_accent
File "/content/vits-finetuning/vits-finetuning/text/japanese.py", line 3, in <module>
    import pyopenjtalk
File "/usr/local/lib/python3.8/dist-packages/pyopenjtalk/__init__.py", line 20, in <module>
    from .htsengine import HTSEngine
File "pyopenjtalk/htsengine.pyx", line 1, in init pyopenjtalk.htsengine
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

因为我这边显卡比较垃圾，batch_size试到4显卡都有点难顶，所以一般线上跑。然后我本地试了一下是可以正常运行的，不知道这边是不是谷歌改了啥东西了...

**Comment by SayaSS** [comment]
我更新了下requirements.txt，重新运行应该就可以了

**Comment by boypjm998** [comment]
十分感谢大佬，亲测可以用了。
顺便我有个疑问关于这个模型过拟合的问题...
我之前用200条语音跑了大概500ep感觉效果挺好的，但是之后换角色，大概700+条语音总计1h+，跑300轮的效果不如200轮，感觉过拟合有点严重，就是说数据集里面的话感觉和原文完全一致，但是说别的话感觉就跑调比较明显。

不知道是数据数量的原因还是什么，我也没把握数据集多了的话，按道理是应该多训练几次还是少训练几次...（一开始我还想加下模型dropout参数，但是最后没敢动模型参数）

**Comment by SayaSS** [comment]
少训练几次试试，可以把eval_interval调低输出步数贴近的模型

**Comment by boypjm998** [comment]
谢谢您的建议，确实是好一些。
但是下午又重新训练了一下，感觉有些奇怪，就是我在使用相同的数据集的情况下，拿您那个G_0和D_0，就是800+个角色的模型覆盖训练，明显不容易过拟合，大概600轮左右达到很好的效果。但是如果用150M那两个-p后缀进行训练，在200轮左右就会出现上述我说的过拟合，且缩短存储步长进行微调，最好的模型效果感觉也一言难尽，就感觉很奇怪....

**Comment by SayaSS** [comment]
可能是因为optimizer我也一块删掉了的原因，手动在config里降低lr试试，例如2e-5

**Comment by wzdacyl** [comment]
@SayaSS 大佬，我用的最新的requirements，但遇到同样的错应该如何解决啊？报错信息如下：
```
$ python preprocess.py --filelists filelist/leo_train.txt filelist/leo_val.txt
Traceback (most recent call last):
  File "preprocess.py", line 2, in <module>
    import text
  File "D:\sourceCode\TTS\vits-finetuning\text\__init__.py", line 2, in <module>
    from text import cleaners
  File "D:\sourceCode\TTS\vits-finetuning\text\cleaners.py", line 2, in <module>
    from text.japanese import japanese_to_romaji_with_accent
  File "D:\sourceCode\TTS\vits-finetuning\text\japanese.py", line 3, in <module>
    import pyopenjtalk
  File "D:\WorkApp\anaconda3\envs\VITS\lib\site-packages\pyopenjtalk\__init__.py", line 20, in <module>
    from .htsengine import HTSEngine
  File "pyopenjtalk/htsengine.pyx", line 1, in init pyopenjtalk.htsengine
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
尝试了一些其他的方法，如https://github.com/MaartenGr/BERTopic/issues/392 中的。但并无法修复
```
pip install --upgrade pip setuptools wheel
pip install bertopic --no-cache-dir
pip uninstall hdbscan -y
pip install hdbscan --no-cache-dir --no-binary :all: --no-build-isolation
```

我的包如下，
```
conda                     23.5.0
hdbscan                   0.8.29
numpy                     1.21.6
python                    3.8.16
```

请大佬帮看看我如何修复这个问题

**Comment by wzdacyl** [comment]
问题通过降低python版本到3.7后暂时解决了，3.8的依然无效
