### ISSUE TITLE
Single-Speaker Pre-Trained Model

### ISSUE THREAD

**Issue by MikuAuahDark** [SayaSS/vits-finetuning#8]
Is there a pre-trained model for single-speaker mode (`n_speakers = 0` which uses `train.py` for training) which I can use for finetune, or does the `G_0-p` and `D_0-p` is what I need? Thanks.

**Comment by SayaSS** [comment]
Yes, you can use `G_0-p` and `D_0-p` with the `configs/config-single-speaker.json`.

**Comment by MikuAuahDark** [comment]
Thank you.
