### ISSUE TITLE
关于monotonic_align的问题

### ISSUE THREAD

**Issue by Apoil** [SayaSS/vits-finetuning#9]
当我到\monotonic_align目录下，运行指令：python setup.py build_ext --inplace
这是出来的信息：
![image](https://user-images.githubusercontent.com/29500079/221164667-216f63e8-89ca-4ef2-8aed-682dec0a2d3b.png)
，我以为没什么问题，而当我去根目录运行 python train_ms.py -c configs/config.json -m checkpoints 的时候
出现了这个提示：No module named 'monotonic_align.monotonic_align'
![image](https://user-images.githubusercontent.com/29500079/221165089-7109a5f6-c1d6-41dc-a6be-4b2b46f484d8.png)

我的系统是win11，用的是python 3.10.10  
之前试过python3.11.2/ 3.8.10/3.9 requirements里的pyopenjtalk用pip装不上，直接下载包也无法安装，安装上了又少文件，而我试的3.10.10的pip也装不上，但是直接官网下载包就可以装上了。用了python3.10.10环境应该没有问题，现在就不知道如何解决这个问题了

**Comment by SayaSS** [comment]
请确保编译好的`core.cp310-win_amd64.pyd`文件存在于`monotonic_align/monotonic_align`目录下
如果没有的话可以在`build`目录下寻找或者重新编译
```
└── vits-finetuning/
    └── monotonic_align/
        ├── build/
        └── monotonic_align/
            └── core.cp310-win_amd64.pyd

```

**Comment by Apoil** [comment]
> 请确保编译好的`core.cp310-win_amd64.pyd`文件存在于`monotonic_align/monotonic_align`目录下 如果没有的话可以在`build`目录下寻找或者重新编译
> 
> ```
> └── vits-finetuning/
>     └── monotonic_align/
>         ├── build/
>         └── monotonic_align/
>             └── core.cp310-win_amd64.pyd
> ```
谢谢，我从build内lib.win-amd64-cpython-310目录里拷贝出来就解决了
